name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: variable
      id: variable
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: variable
        setup-command: npm install
        command: npm run test:variable
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VARIABLE_RESULTS: "${{steps.variable.outputs.result}}"
      with:
        runners: variable
